# Generated by Django 5.2.3 on 2025-06-24 10:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=6, unique=True, verbose_name='Codigo producto')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=10, verbose_name='Serie de factura')),
                ('numberInvoice', models.IntegerField(default=1, unique=True, verbose_name='Número de factura')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Titulo')),
                ('customer', models.CharField(blank=True, max_length=100, verbose_name='cliente')),
                ('date', models.DateField(verbose_name='Fecha de creación')),
                ('total', models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='Total')),
                ('lastUpdated', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-lastUpdated'],
                'indexes': [models.Index(fields=['title'], name='crud_invoic_title_3ea68a_idx'), models.Index(fields=['customer'], name='crud_invoic_custome_818813_idx'), models.Index(fields=['date'], name='crud_invoic_date_c21ae1_idx'), models.Index(fields=['total'], name='crud_invoic_total_925407_idx')],
            },
        ),
        migrations.CreateModel(
            name='LineInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='crud.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.product')),
            ],
        ),
    ]
