# Generated by Django 5.2.3 on 2025-06-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='numberInvoice',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=24),
        ),
    ]
