# Generated by Django 5.2.3 on 2025-06-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_invoice_numberinvoice_alter_invoice_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='numberInvoice',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ref',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
